### ISSUE TITLE
conditionally enable or disable enum options

### ISSUE THREAD

**Issue by gwennlbh** [cigaleapp/cigale#106]
Par exemple: les [Allacma fusca](https://jessica-joachim.com/entognathes/collemboles/sminthuridae/allacma-fusca/) peuvent se présenter sous deux variantes, _usignata_ et _pustulata_. 

Si on veut inclure la variante dans les métadonnées du protocole, on pourrait définir un nouvel enum "variant". 

Le pb est que, si l'espece n'est pas l'allacma fusca, ça sert à rien de proposer les variantes usignata et pustulata. L'idée serait donc de contraindre certaines options d'une métadonnée enum aux valeurs d'autres options. Par exemple:

```
...
metadata:
  variant:
    name: Variante
    options:
      - key: usignata
        label: Usignata
        available: metadata.species.valueLabel == "Allacma Fusca" # disponible ssi la metadata species a pour valeur le choix avec label "Allacma Fusca"
      - key: pustulata
        label: Pustulata
        available: metadata.species.valueLabel == "Allacma Fusca"
      - key: ... # on peut imaginer des variantes pour d'autres espèces
```

Et ensuite dans l'interface, les choix sélectionnables seraient conditionés par `metadata.species`. Ça permettrait de moins flooder l'UI avec pleins d'options inutiles.

T'en penses quoi @mcauchoix ?

Quelques questions quand même:

- quel "micro-langage" d'expressions utiliser? hors de question de laisser le protocole interpréter du javascript arbitraire bien sûr (on apelle ça une faille XSS '^^). J'ai fait une recherche rapide:
  - [cel-js](https://www.npmjs.com/package/cel-js) semble pas mal, avec une derniere version published ya 1 mois seulement. Implémente en plus le standard [Common Expressions Language](https://github.com/google/cel-spec) de Google, donc pas de risque de dépendre d'une lib obsolète et de devoir changer de langage et avoir des protocoles qui marchent plus. Sadly c'est un peut "programmer-oriented", avec des "&&" et "||" à la place de "and" et "or" pour les dis/con-jonctions booléennes, par exemple. 
  - Ya aussi [jexl](https://www.npmjs.com/package/jexl), qui permet de définir ses propres opérateurs. Notamment, un opérateur qui fait des comparaisons insensibles à la casse (comme ça si on compare à "allacma fusca" et pas "Allacma Fusca" ça marche quand même) serait vachement bien, mais derniere publication ya 5 ans…
  - [js-feel](https://www.npmjs.com/package/js-feel), qui met l'accent sur la facilité du langage en préférant des mots à des symboles (ya aussi un opérateur "between" vachement appréciable et tres rare en programmation: "foo between 5 and 10"), mais derniere version ya 4 ans malheureusement
- en fait j'ai pas d'autres questions à résoudre pour l'instant ><
