### ISSUE TITLE
human validation tool

### ISSUE THREAD

**Issue by mcauchoix** [cigaleapp/cigale#98]
Hi,
after classification would it be possible to add a link toward this website 
https://jessica-joachim.com/entognathes/collemboles/entomobryidae/entomobrya-albocincta/
so people can check if the picture correspond to the morphological criterium for identifcation?
Thanks!

**Comment by gwennlbh** [comment]
We plan on being showing description of enum-type metadata options in the UI - and we would there make URLs clickable -- would that work here?

Currently, we fill up the possible enum values for the built-in metadata "species" from the classification model's possible classes: https://media.gwen.works/cigale/models/class_mapping.txt

The idea (see #99) is to allow protocols to define the models they want to use for classification inference.

If someone wants to provide links to specific species' photos, for example, they can manually describe their protocol's "species" metadata choices, instead of letting a "classmapping" file define these options:

```yaml
id: whatever
...
metadata:
  species:
    name: Species of the arthropod
    type: enum
    options:
      - key: 0 # 0 == the 0th neuron on the output layer of the classification model
        label: Entomobrya albocincta
        description: Son corps est sombre, avec une bande claire thoracique, la première moitié du 4ème segment abdominal claire et l’apex de l’abdomen clair. Les antennes sont plus claires à la base.
        learnMore: https://jessica-joachim.com/entognathes/collemboles/entomobryidae/entomobrya-albocincta/
     # etc...
...
inference:
  classification:
    model: https:///....
    ...
    metadata: species
```

..and in turn, in the user interface, we would show some help and a link (the "learnMore" property) alongside the value on the side panel

what do you think?

I guess having that much info on the sidepanel means it should be bigger, so this possibly also depends on #53
